name: Ruff

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install UV
      run: |
        pip install uv
    - name: Format code with Ruff
      run: |
        uvx ruff format
    - name: Check code with Ruff
      run: |
        uvx ruff check with Ruff
    