name: Lint and Type Check
permissions:
  contents: read

on:
  push:
    paths:
      - "**.py"
      - "uv.lock"
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: auto

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: uv run ruff check --output-format=github .

      - name: Run Pyright
        uses: jakebailey/pyright-action@v3
        with:
          python-path: .venv/bin/python
